import = ["~/.config/alacritty/themes/themes/sonokai_atlantis.toml"]

[font]
size = 17

[font.bold]
# JetBrainsMono Nerd Font
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 1 

